version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: sf311_pg
    environment:
      POSTGRES_USER: sf311
      POSTGRES_PASSWORD: sf311
      POSTGRES_DB: sf311
      TZ: America/Los_Angeles
    ports:
      - "5433:5432"
    volumes:
      - ./data:/load
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sf311"]
      interval: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: sf311_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - metabase_data:/metabase-data

volumes:
  pgdata:
  metabase_data:
